// Generated by gencpp from file turtle_regulation_kritika_yassir/setWaypointService.msg
// DO NOT EDIT!


#ifndef TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICE_H
#define TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICE_H

#include <ros/service_traits.h>


#include <turtle_regulation_kritika_yassir/setWaypointServiceRequest.h>
#include <turtle_regulation_kritika_yassir/setWaypointServiceResponse.h>


namespace turtle_regulation_kritika_yassir
{

struct setWaypointService
{

typedef setWaypointServiceRequest Request;
typedef setWaypointServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setWaypointService
} // namespace turtle_regulation_kritika_yassir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointService > {
  static const char* value()
  {
    return "5f57f81716b13aa889ea26d3be474da6";
  }

  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointService&) { return value(); }
};

template<>
struct DataType< ::turtle_regulation_kritika_yassir::setWaypointService > {
  static const char* value()
  {
    return "turtle_regulation_kritika_yassir/setWaypointService";
  }

  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointService&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointServiceRequest> should match
// service_traits::MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointService >
template<>
struct MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointService >::value();
  }
  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_regulation_kritika_yassir::setWaypointServiceRequest> should match
// service_traits::DataType< ::turtle_regulation_kritika_yassir::setWaypointService >
template<>
struct DataType< ::turtle_regulation_kritika_yassir::setWaypointServiceRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_regulation_kritika_yassir::setWaypointService >::value();
  }
  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse> should match
// service_traits::MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointService >
template<>
struct MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointService >::value();
  }
  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse> should match
// service_traits::DataType< ::turtle_regulation_kritika_yassir::setWaypointService >
template<>
struct DataType< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_regulation_kritika_yassir::setWaypointService >::value();
  }
  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICE_H
