// Generated by gencpp from file turtle_regulation_kritika_yassir/setWaypointServiceResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICERESPONSE_H
#define TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_regulation_kritika_yassir
{
template <class ContainerAllocator>
struct setWaypointServiceResponse_
{
  typedef setWaypointServiceResponse_<ContainerAllocator> Type;

  setWaypointServiceResponse_()
    : res(false)  {
    }
  setWaypointServiceResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setWaypointServiceResponse_

typedef ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<std::allocator<void> > setWaypointServiceResponse;

typedef boost::shared_ptr< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse > setWaypointServiceResponsePtr;
typedef boost::shared_ptr< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse const> setWaypointServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator1> & lhs, const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator1> & lhs, const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_regulation_kritika_yassir

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_regulation_kritika_yassir/setWaypointServiceResponse";
  }

  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n"
"\n"
;
  }

  static const char* value(const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setWaypointServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_regulation_kritika_yassir::setWaypointServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_REGULATION_KRITIKA_YASSIR_MESSAGE_SETWAYPOINTSERVICERESPONSE_H
